ACTIVATE_HTTPS: true
ANDROID_OAUTH2_SECRET: iJjcdXLMpEFRMuzmcuotwjwN
CMS_HOST: studio.aqlam-sd.net
CONTACT_EMAIL: contact@aqlam-sd.net
DOCKER_IMAGE_OPENEDX: mortada/openedx:3.12.0
EDX_PLATFORM_REPOSITORY: https://github.com/morta10/edx-platform.git
ID: u7utn1lRCynmfUlqphvOf3LR
LANGUAGE_CODE: ar
LMS_HOST: lms.aqlam-sd.net
MYSQL_ROOT_PASSWORD: v4YzS2TI
OPENEDX_MYSQL_PASSWORD: 0yDctEkq
OPENEDX_SECRET_KEY: CGaxo4DrgQ095amWchy1k4Qa
PLATFORM_NAME: Aqlam
