version: "3.7"
services:

    mysql-job:
      image: docker.io/mysql:5.6.36
      entrypoint: []
      command: ["echo", "done"]
    
    lms-job:
      image: docker.io/mortada/openedx:3.12.0
      environment:
        SERVICE_VARIANT: lms
        SETTINGS: ${EDX_PLATFORM_SETTINGS:-tutor.production}
      volumes:
        - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/:ro
        - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/:ro
        - ../apps/openedx/config/:/openedx/config/:ro
    
    cms-job:
      image: docker.io/mortada/openedx:3.12.0
      environment:
        SERVICE_VARIANT: cms
        SETTINGS: ${EDX_PLATFORM_SETTINGS:-tutor.production}
      volumes:
        - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/:ro
        - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/:ro
        - ../apps/openedx/config/:/openedx/config/:ro
    
    forum-job:
      image: docker.io/overhangio/openedx-forum:3.12.3
      environment:
        SEARCH_SERVER: "http://elasticsearch:9200"
        MONGODB_AUTH: ""
        MONGODB_HOST: "mongodb"
        MONGODB_PORT: "27017"
    
    